# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${root}
    password: ${MANdky1223!}
    url: ${jdbc:mysql://localhost:3306/eyedia}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---
# Dev Profile

#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    url: ${DB_URL}
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
---